- name: build docker image
  hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Checkout repos
    git:
     repo: '{{ repo }}'
     dest: '{{ repo_dir }}'
     version: '{{ branch }}'
     force: yes

  - name: build image
    shell: "docker build -f {{ repo_dir }}/docker/Dockerfile -t 'go-graphstore:{{ tag }}' {{ repo_dir }}"

  - name: build image
    shell: "docker build -f {{ repo_dir }}/docker/Dockerfile.proxy -t 'go-apache:{{ tag }}' {{ repo_dir }}/docker"
