- name: build docker image
  hosts: all
  vars_files:
  - vars.yaml

  tasks:
  - name: Checkout repos
    git:
     repo: '{{ repo }}'
     dest: '{{ repo_dir }}'
     version: '{{ branch }}'
     force: yes

  - name: build go-graphstore image
    shell: "docker build -f {{ repo_dir }}/docker/Dockerfile -t '{{ graphstore_image }}' {{ repo_dir }}"

  - name: build go-apache image
    shell: "docker build -f {{ repo_dir }}/docker/Dockerfile.proxy -t '{{ apache_proxy_image }}' {{ repo_dir }}/docker"
