version: '3'
services:
  graphstore:
    hostname: graphstore
    container_name: graphstore 
    image: go-graphstore:{{ tag }}
    environment: 
      - MEM={{ MEM }}
    volumes:
      - {{ stage_dir }}/blazegraph.jnl:/app/blazegraph.jnl
      - {{ stage_dir }}/readonly_cors.xml:/app/conf/readonly_cors.xml
    restart: unless-stopped

  apache_graphstore:
    hostname: apache_graphstore
    container_name: apache_graphstore
    image: go-apache:{{ tag }} 
    environment:
      - USE_S3={{ USE_S3 }}
    restart: unless-stopped
    volumes:
      - {{ stage_dir }}/httpd-vhosts-graphstore.conf:/etc/apache2/sites-enabled/httpd-vhosts-graphstore.conf
      - {{ stage_dir }}/apache_proxy_logs:/var/log/apache2
      - {{ stage_dir }}/apache2:/etc/logrotate.d/apache2
      - {{ stage_dir }}/s3cfg:/opt/credentials/s3cfg
    ports:
      - "80:80"
    depends_on:
      - graphstore
