version: '3.7'
services:
  graphstore:
    hostname: graphstore
    container_name: graphstore 
    image: {{ graphstore_image }}
    init: true
    environment: 
      - MEM={{ MEM }}
    volumes:
      - {{ stage_dir }}/blazegraph.jnl:/app/blazegraph.jnl
      - {{ stage_dir }}/readonly_cors.xml:/app/conf/readonly_cors.xml
    restart: unless-stopped

  apache_graphstore:
    hostname: apache_graphstore
    container_name: apache_graphstore
    image: {{ apache_proxy_image }} 
    init: true
    environment:
      - USE_S3={{ USE_S3 }}
      - S3_PATH={{ S3_PATH }}
      - S3_BUCKET={{ S3_BUCKET }}
    restart: unless-stopped
    volumes:
      - {{ stage_dir }}/proxy-configs/s3cfg:/opt/credentials/s3cfg
      - {{ stage_dir }}/proxy-configs/httpd-vhosts-graphstore.conf:/etc/apache2/sites-enabled/httpd-vhosts-graphstore.conf
      - {{ stage_dir }}/apache_proxy_logs:/var/log/apache2
    ports:
      - "80:80"
    depends_on:
      - graphstore
